### PR TITLE
Missing Commits from Fuzion's repo 

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks - I think these are both in 4.6.9 release?

NB - not quite sure how we'll do it this time - but in 4.4 once I started adding patches that weren't in the next point version I started editing the commit message to say what Civi version they would be in

**Comment by seamuslee001** [comment]
I think they have only gone into master branch which may mean they get missed from 4.6

**Comment by eileenmcnaughton** [comment]
ok

**Comment by eileenmcnaughton** [comment]
They might be LTS candidates - esp the first one

**Pull request merged**
