### PR TITLE
CRM-18046 Remove unnecessary permission check on search link in ABtes…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ting reports

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Actually - I'm about to put 4.6.13 out on your site - so that is the latest branch now

**Comment by seamuslee001** [comment]
ur git hub was defaulting to 4.6.12.0. I have already dealt with this on ours. Also PRs are at core as well

**Comment by eileenmcnaughton** [comment]
That's fixed now :-) There is a 4.6.13 release on Wed due to a regression in 4.6.12 on views code

**Comment by seamuslee001** [comment]
just pred against 4.6.13.0 branch for ya

**Comment by eileenmcnaughton** [comment]
Cool - please check the Redmine message I just sent you!

**Pull request merged**
