### PR TITLE
Partial revert of d5ecf8e2d1ccf9769517a837f8807521792e31fa due to dif…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ferences between core and fuzion repos

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton This was picked up during AUG testing, my original commit works fine on core but because fuzion has reverted stuff that is in core, we need to revert this part of a patch

**Comment by xurizaemon** [comment]
Hey Seamus, any chance you can link to what was picked up as not working in AUG testing?

**Comment by seamuslee001** [comment]
@xurizaemon This test for us was failing https://contact-nsw.ubox.greens.org.au/agc/test/some/group::create basically trying to create a group using the group.create API call failed because when you get down to it in the CRM_Contact_BAO_Query in the function called group. it looks for groupids as the array_keys of the passed in $value array

**Comment by seamuslee001** [comment]
@xurizaemon https://github.com/fuzionnz/civicrm-core/blob/4.6.21.0/CRM/Contact/BAO/Group.php#L485 calls 
https://github.com/fuzionnz/civicrm-core/blob/4.6.21.0/CRM/Contact/BAO/GroupContactCache.php#L220
Which in turn eventually gets to https://github.com/fuzionnz/civicrm-core/blob/4.6.21.0/CRM/Contact/BAO/Query.php#L2862
and https://github.com/fuzionnz/civicrm-core/blob/4.6.21.0/CRM/Contact/BAO/Query.php#L2877

**Comment by seamuslee001** [comment]
Those last couple of lines are quite different in core v fuzion as they got reverted back when AUG had major issues with group caching.

**Pull request merged**
